### ISSUE TITLE
TL-WR942N WPS file can not load after installation

### ISSUE THREAD

**Issue by APToni** [xchwarze/wifi-pineapple-community#6]
Hi, WPS file cannot load after installation, may you now what is the problem please? TL-WR942N.

**Comment by xchwarze** [comment]
Hi!
The scope of this repo is only the updatable content of the pineapple (original or "community").
Basically
[docs](https://github.com/xchwarze/wifi-pineapple-community/tree/main/docs)
[modules](https://github.com/xchwarze/wifi-pineapple-community/tree/main/modules)
[packages](https://github.com/xchwarze/wifi-pineapple-community/tree/main/packages)
[themes](https://github.com/xchwarze/wifi-pineapple-community/tree/main/themes)

Without seeing an error trace I don't know what might be wrong, but if it's something related to wpad you can do a custom build with the KARMA code block mentioned above and it should fix it.
https://github.com/xchwarze/wifi-pineapple-cloner/blob/master/tools/fs-patcher.sh#L69

**Comment by xchwarze** [comment]
Hi!
The scope of this repo is only the updatable content of the pineapple (original or "community").
Basically
[docs](https://github.com/xchwarze/wifi-pineapple-community/tree/main/docs)
[modules](https://github.com/xchwarze/wifi-pineapple-community/tree/main/modules)
[packages](https://github.com/xchwarze/wifi-pineapple-community/tree/main/packages)
[themes](https://github.com/xchwarze/wifi-pineapple-community/tree/main/themes)

Anyway, without seeing an error trace I don't know what might be wrong, but if it's something related to wpad you can do a custom build with the KARMA code block mentioned above and it should fix it.
https://github.com/xchwarze/wifi-pineapple-cloner/blob/master/tools/fs-patcher.sh#L69

**Comment by m5kro** [comment]
Hi @APToni,
Are you perhaps talking about the WPS module? If so, I am already looking into why it stopped working on the latest firmware. If you need WPS functionality right now you could use Reaver and Wash using ssh.

**Comment by APToni** [comment]
Hi m5kro, That's right, I have a tetra HAK5, it has the same problems on the new firmware. I understand this is normal with WPS.
I installed Reaver and Wash.

**Comment by xchwarze** [comment]
The title without the word "MODULE" meant something else.
You also didn't attach any info for someone to really help you...

**Comment by APToni** [comment]
The problem with the **MODULE** wps is more than five years old, I very much doubt that the problem will be solved.

**Comment by xchwarze** [comment]
You have no idea what you are talking about because the dependencies used by the module are updated with the latest binaries which are from 2021 or 2022 and the module code is updated in 2023.
https://github.com/xchwarze/wifi-pineapple-community/pull/2

**Comment by APToni** [comment]
Of course, that's just why the module still doesn't work, and clinging to words is your style.  People ask you questions, you simply turn them off, citing your know-it-all position.  I tried to ask questions correctly, but you still insist on your opinion.

**Comment by xchwarze** [comment]
It is normal in open projects that issues that do not provide evidence are closed after several days.
As usual in the issues you open you never give the minimum of information to help you.
We already had to guess what problem you had, now you want us to do some kind of paranormal debugging with a ouija board or something similar?

**Comment by m5kro** [comment]
WPS module issues have been fixed. New pull request #7
